services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tick-services
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - tickitz-net

  redis:
    image: redis:8.4
    container_name: myrds
    networks:
      - tickitz-net
    volumes:
      - redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server --requirepass ${RDS_PASS}

  postgres:
    image: postgres:17.7-alpine3.23
    container_name: dbsb
    env_file: .env.local
    networks:
      - tickitz-net
    volumes:
      - pg-data:/var/lib/postgresql/data

  nginx:
    image: nginx:mainline-alpine3.23
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
networks:
  tickitz-net:

volumes:
  pg-data:
    external: true
  redis:
    external: true
