services:
  ssh-server:
    build:
      #context menggunakan titik di karenakan 1 direktori dengan dockerfile
      context: .
      dockerfile: Dockerfile
    # image: digunakan jika image sudah ada
    networks:
      - bridge
    volumes:
      - pg-data:/var/lib/postgresql/data containerPath:ro
  postgres:
    1image: #image psotgres
    env_file:
      - ../psql/.env
    environment:
networks:
  my_net: external:true
